---
title: "Plot Sex Stratified estimates for BRACO and cumulative ELA"
author: "SYC"
date: "2026-05-03"
output: html_document
---

## Fig S2
### BRACO vs SPRESTO/GUSTO
```{r}

gsb_m <- gsb %>%
  filter(sex == "Male")
  
gsb_f <- gsb %>%
  filter(sex == "Female")

```

### Males
```{r}

# Use map (a better for-loop) to run the models and combine them
all_results <- map_df(cory, function(out) {
  # Run the model for the specific outcome
  formula <- as.formula(paste(out, "~ braco + ScanAge"))
  model <- lm(formula, data = gsb_m)
  
  # Turn the model results into a data frame
  tidy(model, conf.int = TRUE) %>%
    mutate(outcome_var = out) # Keep track of which model this is
})

# Filter to show ONLY the 'Group' effect across all outcomes
gsb_m_p <- all_results %>% 
  filter(term == "braco") %>%
  mutate(
    p_label = ifelse(p.value < .001, "p < .001", paste0("p = ", round(p.value, 3))),
    is_sig = ifelse(p.value < 0.05, "bold", "plain")
  ) %>%
  mutate(model = outcome_var) %>%
  mutate(model = str_replace(model, fixed("gpb_pred_"), ""))  %>%
  separate(model, c("Feature", "Type"), "_") %>%
  mutate(Feature = toupper(Feature)) %>%
  mutate(Type = ifelse(
    Type == "sex", "Full-Span", ifelse(
    Type == "phase", "Phase-Specific", Type
  ))) %>%
  mutate(Feature = factor(Feature, levels = rev(c("S1", "S2", "F1", "A1", "A2", "A3")))) %>%
  mutate(Type = factor(Type, levels = c("Full-Span", "Phase-Specific")))


```

### Females
```{r}

# Use map (a better for-loop) to run the models and combine them
all_results <- map_df(cory, function(out) {
  # Run the model for the specific outcome
  formula <- as.formula(paste(out, "~ braco + ScanAge"))
  model <- lm(formula, data = gsb_f)
  
  # Turn the model results into a data frame
  tidy(model, conf.int = TRUE) %>%
    mutate(outcome_var = out) # Keep track of which model this is
})

# Filter to show ONLY the 'Group' effect across all outcomes
gsb_f_p <- all_results %>% 
  filter(term == "braco") %>%
  mutate(
    p_label = ifelse(p.value < .001, "p < .001", paste0("p = ", round(p.value, 3))),
    is_sig = ifelse(p.value < 0.05, "bold", "plain")
  ) %>%
  mutate(model = outcome_var) %>%
  mutate(model = str_replace(model, fixed("gpb_pred_"), ""))  %>%
  separate(model, c("Feature", "Type"), "_") %>%
  mutate(Feature = toupper(Feature)) %>%
  mutate(Type = ifelse(
    Type == "sex", "Full-Span", ifelse(
    Type == "phase", "Phase-Specific", Type
  ))) %>%
  mutate(Feature = factor(Feature, levels = rev(c("S1", "S2", "F1", "A1", "A2", "A3")))) %>%
  mutate(Type = factor(Type, levels = c("Full-Span", "Phase-Specific")))


```

#### Plot
```{r}

gsb_m_plot <- gsb_m_p %>%
  ggplot(aes(x = estimate, y = Feature)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") + # Null line
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.1) +
  geom_point(size = 2.2, color = "midnightblue", shape = 18) +
  geom_text(aes(label = p_label, fontface = is_sig), 
            vjust = -1, size = 2) +
  facet_grid(Type ~ ., scales = "free_y", space = "free_y") + 
  # Expand the y-axis slightly so labels don't get cut off at the top
  scale_y_discrete(expand = expansion(add = c(0.5, 1))) +
  theme_minimal(base_size = 8) +  
  labs(
    title = "Early-Childhood: BRACO relative to GUSTO/S-PRESTO",
    subtitle = "N = 212",
    x = "Regression Coefficient (95% CI)",
    y = "BrainAge Model"
  ) + 
  theme(            
    panel.spacing = unit(1, "lines"),         # Adds a bit of gap between groups
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, face = "italic")  
    ) 

gsb_m_plot

```

#### Plot
```{r}

gsb_f_plot <- gsb_f_p %>%
  ggplot(aes(x = estimate, y = Feature)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") + # Null line
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.1) +
  geom_point(size = 2.2, color = "midnightblue", shape = 18) +
  geom_text(aes(label = p_label, fontface = is_sig), 
            vjust = -1, size = 2) +
  facet_grid(Type ~ ., scales = "free_y", space = "free_y") + 
  # Expand the y-axis slightly so labels don't get cut off at the top
  scale_y_discrete(expand = expansion(add = c(0.5, 1))) +
  theme_minimal(base_size = 8) +  
  labs(
    title = "Early-Childhood: BRACO relative to GUSTO/S-PRESTO",
    subtitle = "N = 147",
    x = "Regression Coefficient (95% CI)",
    y = "BrainAge Model"
  ) + 
  theme(            
    panel.spacing = unit(1, "lines"),         # Adds a bit of gap between groups
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, face = "italic")  
    ) 

gsb_f_plot

```

```{r}

setwd('/figs/supp/sex-stratified')

pdf(file="gsb_m_plot.pdf", width=4, height=3)
gsb_m_plot
dev.off()

pdf(file="gsb_f_plot.pdf", width=4, height=3)
gsb_f_plot
dev.off()

```

### ELA
```{r}

ela_m <- df.ela %>%
  filter(sex == "Male")
  
ela_f <- df.ela %>%
  filter(sex == "Female")

```

### Males
```{r}

# Use map to run the models and combine them
all_results <- map_df(cory, function(out) {
  
  formula <- as.formula(paste(out, "~ A_index_prenatal + ScanAge"))
  model <- lm(formula, data = ela_m)
  
  # Turn the model results into a data frame
  tidy(model, conf.int = TRUE) %>%
    mutate(outcome_var = out) 
})

# Filter to show ONLY the 'Group' effect across all outcomes
ela_m_p <- all_results %>% 
  filter(term == "A_index_prenatal") %>%
  mutate(
    p_label = ifelse(p.value < .001, "p < .001", paste0("p = ", round(p.value, 3))),
    is_sig = ifelse(p.value < 0.05, "bold", "plain")
  ) %>%
  mutate(model = outcome_var) %>%
  mutate(model = str_replace(model, fixed("gpb_pred_"), ""))  %>%
  separate(model, c("Feature", "Type"), "_") %>%
  mutate(Feature = toupper(Feature)) %>%
  mutate(Type = ifelse(
    Type == "sex", "Full-Span", ifelse(
    Type == "phase", "Phase-Specific", Type
  ))) %>%
  mutate(Feature = factor(Feature, levels = rev(c("S1", "S2", "F1", "A1", "A2", "A3")))) %>%
  mutate(Type = factor(Type, levels = c("Full-Span", "Phase-Specific")))

```

### Females
```{r}

# Use map to run the models and combine them
all_results <- map_df(cory, function(out) {
  
  formula <- as.formula(paste(out, "~ A_index_prenatal + ScanAge"))
  model <- lm(formula, data = ela_f)
  
  # Turn the model results into a data frame
  tidy(model, conf.int = TRUE) %>%
    mutate(outcome_var = out) 
})

# Filter to show ONLY the 'Group' effect across all outcomes
ela_f_p <- all_results %>% 
  filter(term == "A_index_prenatal") %>%
  mutate(
    p_label = ifelse(p.value < .001, "p < .001", paste0("p = ", round(p.value, 3))),
    is_sig = ifelse(p.value < 0.05, "bold", "plain")
  ) %>%
  mutate(model = outcome_var) %>%
  mutate(model = str_replace(model, fixed("gpb_pred_"), ""))  %>%
  separate(model, c("Feature", "Type"), "_") %>%
  mutate(Feature = toupper(Feature)) %>%
  mutate(Type = ifelse(
    Type == "sex", "Full-Span", ifelse(
    Type == "phase", "Phase-Specific", Type
  ))) %>%
  mutate(Feature = factor(Feature, levels = rev(c("S1", "S2", "F1", "A1", "A2", "A3")))) %>%
  mutate(Type = factor(Type, levels = c("Full-Span", "Phase-Specific")))

```

#### Plot
```{r}

ela_m_plot <- ela_m_p %>%
  ggplot(aes(x = estimate, y = Feature)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") + # Null line
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.1) +
  geom_point(size = 2.2, color = "midnightblue", shape = 18) +
  geom_text(aes(label = p_label, fontface = is_sig), 
            vjust = -1, size = 2) +
  facet_grid(Type ~ ., scales = "free_y", space = "free_y") + 
  # Expand the y-axis slightly so labels don't get cut off at the top
  scale_y_discrete(expand = expansion(add = c(0.5, 1))) +
  theme_minimal(base_size = 8) +  
  labs(
    title = "Early-Childhood: Cumulative Early Life Adversity (ELA)",
    subtitle = "N = 54",
    x = "Regression Coefficient (95% CI)",
    y = "BrainAge Model"
  ) + 
  theme(            
    panel.spacing = unit(1, "lines"),         # Adds a bit of gap between groups
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, face = "italic")  
    ) 

ela_m_plot

```

#### Plot
```{r}

ela_f_plot <- ela_f_p %>%
  ggplot(aes(x = estimate, y = Feature)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") + # Null line
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.1) +
  geom_point(size = 2.2, color = "midnightblue", shape = 18) +
  geom_text(aes(label = p_label, fontface = is_sig), 
            vjust = -1, size = 2) +
  facet_grid(Type ~ ., scales = "free_y", space = "free_y") + 
  # Expand the y-axis slightly so labels don't get cut off at the top
  scale_y_discrete(expand = expansion(add = c(0.5, 1))) +
  theme_minimal(base_size = 8) +  
  labs(
    title = "Early-Childhood: Cumulative Early Life Adversity (ELA)",
    subtitle = "N = 43",
    x = "Regression Coefficient (95% CI)",
    y = "BrainAge Model"
  ) + 
  theme(            
    panel.spacing = unit(1, "lines"),         # Adds a bit of gap between groups
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, face = "italic")  
    ) 

ela_f_plot

```

```{r}

setwd('/figs/supp/sex-stratified')

pdf(file="ela_m_plot.pdf", width=4, height=3)
ela_m_plot
dev.off()

pdf(file="ela_f_plot.pdf", width=4, height=3)
ela_f_plot
dev.off()

```


